name: Retreat
favicon: null
layout_spectrum: 0.99922
typography_spectrum: 0.75442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e5d8b'
    - '#030303'
    - '#678cc1'
    - '#2e332c'
    - '#e2cba9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
