name: Retreat
favicon: null
layout_spectrum: 0.9089099855627865
typography_spectrum: 0.75442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9859841510187835
  lightness: 0.3262921338900924
  saturation: 0.07598179718479514
  rhythmicContrast: 0.892179770860821
purpose: []
